language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

matrix:
  allow_failures:
    - php: 7.0
    - php: nightly
    - php: hhvm
  fast_finish: true