language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
  fast_finish: true

notifications:
  email:
    on_failure: always
    on_success: never

build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coveragefile'
                coverage:
                    file: 'coveragefile'
                    format: 'php-clover'
